export const ActionTypes = {
  SET_BOOKS: "SET_BOOKS",
  SET_SELECTED_BOOK: "SET_SELECTED_BOOK",
  REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",
  SET_VIEW: "SET_VIEW",
  SET_FILTERED_BOOKS: "SET_FILTERED_BOOKS",
  SET_IS_OPEN: "SET_IS_OPEN",
};
